wrappers:
  PixelAggregation:
    aggregation_fn: avg
methods:
  - Gradient
  - InputXGradient
  - GuidedBackprop
  - Deconvolution
  - GradCAM
  - GuidedGradCAM
  - DeepLift
  - IntegratedGradients:
      type: IntegratedGradients
      internal_batch_size: 16
      num_steps: 25
  - SmoothGrad:
      type: SmoothGrad
      stdev: 0.15
      num_samples: 50
  - VarGrad:
      type: VarGrad
      stdev: 0.15
      num_samples: 50
  - DeepShap:
      type: DeepShap
      n_baseline_samples: 100
  - KernelShap:
      type: KernelShap
      n_segments: 50
      n_samples: 300
      super_pixels: True
  - ExpectedGradients:
      type: ExpectedGradients
      num_samples: 100
  - LIME:
      type: ImageLime
      n_segments: 50
      n_samples: 300
